### ISSUE TITLE
Error: illegal operands `andi a1,a1,4095'

### ISSUE THREAD

**Issue by rwmjones** [nojb/riscv-ocaml#1]
In the ocaml omake program, compilation fails with:
```
/tmp/camlasm85c0d6.s:1973: Error: illegal operands `andi a1,a1,4095'
/tmp/camlasm85c0d6.s:2031: Error: illegal operands `andi a1,a1,4095'
/tmp/camlasm85c0d6.s:2037: Error: illegal operands `andi a1,a4,4095'
/tmp/camlasm85c0d6.s:2044: Error: illegal operands `andi a1,a7,4095'
/tmp/camlasm85c0d6.s:2067: Error: illegal operands `andi a1,s2,4095'
/tmp/camlasm85c0d6.s:2074: Error: illegal operands `andi a1,s6,4095'
/tmp/camlasm85c0d6.s:2276: Error: illegal operands `andi a1,a1,4095'
/tmp/camlasm85c0d6.s:2431: Error: illegal operands `andi a1,a1,4095'
/tmp/camlasm85c0d6.s:2437: Error: illegal operands `andi a1,a4,4095'
/tmp/camlasm85c0d6.s:2444: Error: illegal operands `andi a1,a7,4095'
/tmp/camlasm85c0d6.s:2467: Error: illegal operands `andi a1,s2,4095'
/tmp/camlasm85c0d6.s:2474: Error: illegal operands `andi a1,s6,4095'
File "lm_hash.ml", line 1:
Error: Assembler error, input left in file /tmp/camlasm85c0d6.s
```

**Comment by rwmjones** [comment]
This is a copy of the generated assembler:
http://oirase.annexia.org/tmp/camlasm85c0d6.s

**Comment by rwmjones** [comment]
There's another error compiling ocaml pcre.  It's very similar so I'll leave it under the same issue:

```
/tmp/camlasmc421b5.s: Assembler messages:
/tmp/camlasmc421b5.s:1840: Error: illegal operands `ori s2,t4,2049'
/tmp/camlasmc421b5.s:5557: Error: illegal operands `ori s6,s5,2081'
/tmp/camlasmc421b5.s:6539: Error: illegal operands `ori a1,a0,2081'
File "lib/pcre.ml", line 1:
Error: Assembler error, input left in file /tmp/camlasmc421b5.s
```

**Comment by nojb** [comment]
Thanks for the report.  I think I know what is the problem.  I will try to get a fix out ASAP.

**Comment by nojb** [comment]
I think somewhere along the way there has been a change in the range of immediate arguments for the `andi`, `ori` and `xori` instructions.  I pushed a fix to `trunk`.  I am running the OCaml testsuite to make sure there is no regression.  If you could try it out with `omake` & co and report back that would be great.

**Comment by nojb** [comment]
Testsuite passes; I wait for your confirmation before closing this.

**Comment by rwmjones** [comment]
I'm building everything again at the moment (status is right at the bottom of this page: https://fedorapeople.org/groups/risc-v/logs/status.html).  Currently looking good, but the build has not yet reached the previously problematic packages (omake, pcre), so let's wait and see how it goes.

camlp5 is expected to fail.

**Comment by rwmjones** [comment]
[omake](https://fedorapeople.org/groups/risc-v/logs/ocaml-omake/0.9.8.6-0.rc1.fc26.23/build.log) and [pcre](https://fedorapeople.org/groups/risc-v/logs/ocaml-pcre/7.2.3-1.fc26/build.log) builds were successful with this patch.

**Comment by nojb** [comment]
Great, thanks!
