### ISSUE TITLE
4.06.0 release possible?

### ISSUE THREAD

**Issue by oaken-source** [nojb/riscv-ocaml#3]
I have seen the 4.06 branch - is that in a shape that a release can be produced?

Best,
A

**Comment by nojb** [comment]
Yes, indeed, that branch "is" the release (see [announcement](https://inbox.ocaml.org/caml-list/CAPunWhApp7QTJOz=9Ki9h48p+TpnRNAxEqff9TnGDcmQdtMUrQ@mail.gmail.com/)). But indeed I forgot to tag it.

I will sync with upstream 4.06.1 and tag it.

Thanks for the reminder!

**Comment by nojb** [comment]
I tagged 4.06.0 release at https://github.com/nojb/riscv-ocaml/releases/tag/4.06.0%2Briscv.
I am testing 4.06.1 but my `qemu` setup is a bit broken at the moment, so it will take me a bit longer to update.
