### ISSUE TITLE
Cross compilation

### ISSUE THREAD

**Issue by threonorm** [nojb/riscv-ocaml#4]
Hi,

I tried to cross-compile with gcc 7.2.0, but when I do:
``./configure -target riscv64-unknown-elf `` (or linux-gnu)

I get an ERROR that the C compiler is not ISO C compliant. (With the unknown-elf compile I get that the error comes from a synta error in ./tst, an unterminated quoted string).

Is it because cross compilation is not supported yet (and i am supposed to build directly on a riscv host)? Or is it because I am using an unsupported version of riscv-tools ? (commit 84e9d5bf515908d15215cd8ee5b5beb6f7519491 of riscv-tools).

**Comment by nojb** [comment]
Hello @threonorm. Thanks for the interest!

The OCaml compiler does not yet support cross-compilation (at least out-of-the-box), so for now the only way is to build on a RISC-V host (either hardware or in software, using e.g. qemu).

**Comment by threonorm** [comment]
Great, thanks
